#!/usr/bin/env bash

commands() {
  tmux show-options -g -v @COMMANDS 2> /dev/null || builtin history
}

commands | fzf --no-sort --prompt " "

(fzf --reverse --header Commands) <<EOF
cargo run
cargo test
go run main.go
go test -v .
EOF
